# Generated by Django 3.1.7 on 2021-04-01 15:11

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events2Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default='event_2021-04-01', max_length=30)),
                ('queue', models.IntegerField(default=30)),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('ReadyToPost', 'Ready To Post'), ('Posted', 'Posted')], default='ReadyToPost', max_length=15)),
                ('price', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('post_date', models.DateTimeField(blank=True, null=True, verbose_name='datetime for posting')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 11, 46, 574073, tzinfo=utc), verbose_name='event date_from')),
                ('date_to', models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 11, 46, 574117, tzinfo=utc), verbose_name='event date_to')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('price', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 11, 46, 516881, tzinfo=utc), verbose_name='event date_from')),
                ('date_to', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 15, 11, 46, 516934, tzinfo=utc), verbose_name='event date_to')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=30)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(blank=True, default='')),
                ('image', models.CharField(blank=True, max_length=250)),
                ('url', models.CharField(blank=True, max_length=250)),
                ('price', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('date_from', models.DateTimeField(default=datetime.datetime(2021, 4, 3, 15, 11, 46, 572978, tzinfo=utc), verbose_name='event date_from')),
                ('date_to', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 3, 15, 11, 46, 573023, tzinfo=utc), verbose_name='event date_to')),
            ],
        ),
        migrations.CreateModel(
            name='PostingTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_weekday', models.IntegerField(default=4)),
                ('end_weekday', models.IntegerField(default=6)),
                ('posting_time_hours', models.IntegerField(default=13)),
                ('posting_time_minutes', models.IntegerField(default=20)),
            ],
        ),
    ]
