# Generated by Django 3.1.7 on 2021-03-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChannelEvents",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("title", models.CharField(max_length=250)),
                ("date_from", models.DateTimeField(verbose_name="event date_from")),
                ("price", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField()),
                ("title", models.CharField(max_length=250)),
                ("text", models.CharField(max_length=1000)),
                ("price", models.CharField(max_length=150)),
                ("address", models.CharField(max_length=200)),
                ("date_from", models.DateTimeField(verbose_name="event date_from")),
                ("date_to", models.DateTimeField(verbose_name="event date_to")),
            ],
        ),
    ]
