# Generated by Django 3.1.7 on 2021-03-05 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='pub_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time'),
        ),
    ]
