# Generated by Django 3.1.7 on 2021-04-08 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 43, 564822, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 43, 564867, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(default='event_2021-04-08', max_length=30),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 43, 507327, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 8, 56, 43, 507376, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 43, 563563, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 8, 56, 43, 563614, tzinfo=utc), verbose_name='event date_to'),
        ),
    ]
