# Generated by Django 3.1.7 on 2021-03-06 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_pub_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events2Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(default='')),
                ('image', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('ReadyToPost', 'Ready To Post'), ('Posted', 'Posted')], max_length=15)),
                ('price', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('post_date', models.DateTimeField(verbose_name='datetime for posting')),
                ('date_from', models.DateTimeField(verbose_name='event date_from')),
                ('date_to', models.DateTimeField(verbose_name='event date_to')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(default='')),
                ('image', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('date_from', models.DateTimeField(verbose_name='event date_from')),
                ('date_to', models.DateTimeField(verbose_name='event date_to')),
            ],
        ),
        migrations.CreateModel(
            name='EventsNotApprovedOld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('post', models.TextField(default='')),
                ('image', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('date_from', models.DateTimeField(verbose_name='event date_from')),
                ('date_to', models.DateTimeField(verbose_name='event date_to')),
            ],
        ),
        migrations.RemoveField(
            model_name='events',
            name='text',
        ),
        migrations.AddField(
            model_name='events',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
