# Generated by Django 3.1.7 on 2021-04-08 08:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210408_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 50, 500667, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 50, 500709, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 50, 436222, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 8, 56, 50, 436301, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 10, 8, 56, 50, 499533, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 10, 8, 56, 50, 499580, tzinfo=utc), verbose_name='event date_to'),
        ),
    ]
