# Generated by Django 3.1.7 on 2021-03-22 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210306_1240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChannelEvents',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.AddField(
            model_name='events2post',
            name='queue',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 19, 39, 35, 390600, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 19, 39, 35, 390629, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='post',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='post_date',
            field=models.DateTimeField(blank=True, verbose_name='datetime for posting'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='price',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='status',
            field=models.CharField(choices=[('ReadyToPost', 'Ready To Post'), ('Posted', 'Posted')], default='ReadyToPost', max_length=15),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 19, 39, 35, 335497, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 19, 39, 35, 335549, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='post',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='price',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 24, 19, 39, 35, 389750, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 24, 19, 39, 35, 389789, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='image',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='post',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='price',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
