# Generated by Django 3.1.7 on 2021-03-23 13:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20210322_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 56, 21, 114580, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 56, 21, 114607, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(default='event_2021-03-23', max_length=30),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='queue',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 56, 21, 55618, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 13, 56, 21, 55666, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='event_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 56, 21, 113734, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 13, 56, 21, 113775, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='event_id',
            field=models.CharField(max_length=30),
        ),
    ]
