# Generated by Django 3.1.7 on 2022-07-16 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220716_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(default='event10_2022-07-16', max_length=30),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 19, 37, 18, 133745, tzinfo=utc), verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 19, 37, 18, 133745, tzinfo=utc), verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 19, 37, 18, 103714, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 18, 19, 37, 18, 103737, tzinfo=utc), verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 18, 19, 37, 18, 133476, tzinfo=utc), verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 18, 19, 37, 18, 133491, tzinfo=utc), verbose_name='event to_date'),
        ),
    ]
