# Generated by Django 3.1.7 on 2021-03-23 18:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210323_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 18, 31, 34, 768697, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='date_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 18, 31, 34, 768806, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 18, 31, 34, 695559, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 18, 31, 34, 695612, tzinfo=utc), verbose_name='event date_to'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 18, 31, 34, 767853, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='date_to',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 25, 18, 31, 34, 767891, tzinfo=utc), verbose_name='event date_to'),
        ),
    ]
