# Generated by Django 3.1.7 on 2023-03-10 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20220716_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(default='event39_2023-03-10', max_length=30),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 10, 45, 57, 233516, tzinfo=utc), verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 10, 45, 57, 233516, tzinfo=utc), verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 10, 45, 57, 202974, tzinfo=utc), verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 10, 45, 57, 202999, tzinfo=utc), verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='from_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 12, 10, 45, 57, 233245, tzinfo=utc), verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='to_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 10, 45, 57, 233261, tzinfo=utc), verbose_name='event to_date'),
        ),
    ]
