# Generated by Django 3.1.7 on 2023-08-01 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230723_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsnotapprovednew',
            name='full_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
