# Generated by Django 4.2 on 2026-07-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_add_event_embeddings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events2post",
            name="status",
            field=models.CharField(
                choices=[
                    ("ReadyToPost", "Ready To Post"),
                    ("Posted", "Posted"),
                    ("ForFuture", "For Future"),
                    ("OnlyApi", "OnlyApi"),
                    ("Spam", "Spam"),
                    ("Scrape", "Scrape It"),
                    ("Error", "Error"),
                    ("Rejected", "Rejected"),
                    ("Expired", "Expired"),
                    ("Duplicate", "Duplicate"),
                ],
                db_index=True,
                default="ReadyToPost",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="events2post",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("TG", "Telegram"),
                    ("AI", "AI"),
                    ("KASSIR", "kassir"),
                    ("CFG", "config"),
                    ("AFISHA", "afisha"),
                    ("YA", "yandex"),
                    ("TRIPSTER", "tripster"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventsnotapprovednew",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("TG", "Telegram"),
                    ("AI", "AI"),
                    ("KASSIR", "kassir"),
                    ("CFG", "config"),
                    ("AFISHA", "afisha"),
                    ("YA", "yandex"),
                    ("TRIPSTER", "tripster"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventsnotapprovedproposed",
            name="source",
            field=models.CharField(
                choices=[
                    ("TIMEPAD", "Timepad"),
                    ("RADARIO", "Radario"),
                    ("TC", "Ticketscloud"),
                    ("QT", "QTickets"),
                    ("CLTR", "culture"),
                    ("MTS", "MTS"),
                    ("VK", "VK"),
                    ("TG", "Telegram"),
                    ("AI", "AI"),
                    ("KASSIR", "kassir"),
                    ("CFG", "config"),
                    ("AFISHA", "afisha"),
                    ("YA", "yandex"),
                    ("TRIPSTER", "tripster"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
