# Generated by Django 3.1.7 on 2023-08-01 13:24

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_add_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(default=events.models.random_event_id, max_length=30),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='from_date',
            field=models.DateTimeField(default=events.models.default_event_date, verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='post',
            field=models.TextField(blank=True, default='* августа*  фестиваль *«ааааа»*\n\n\n\n*Где:*\n*Когда:*\n*Вход:*'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='to_date',
            field=models.DateTimeField(default=events.models.default_event_date, verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='explored_date',
            field=models.DateTimeField(verbose_name='published date and time'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='from_date',
            field=models.DateTimeField(verbose_name='event date_from'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovednew',
            name='to_date',
            field=models.DateTimeField(blank=True, verbose_name='event to_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='explored_date',
            field=models.DateTimeField(verbose_name='published date and time'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='from_date',
            field=models.DateTimeField(verbose_name='event from_date'),
        ),
        migrations.AlterField(
            model_name='eventsnotapprovedold',
            name='to_date',
            field=models.DateTimeField(blank=True, verbose_name='event to_date'),
        ),
    ]
