# Generated by Django 3.1.7 on 2023-08-31 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_testeventplace'),
        ('events', '0011_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsnotapprovednew',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place'),
        ),
        migrations.AddField(
            model_name='eventsnotapprovedold',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place'),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='post',
            field=models.TextField(blank=True, default='* сентября*  фестиваль *«ааааа»*\n\n\n\n*Где:*\n*Когда:*\n*Вход:*'),
        ),
    ]
