# Generated by Django 3.1.7 on 2024-05-12 07:42

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20240512_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsnotapprovednew',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='events2post',
            name='post',
            field=models.TextField(blank=True, default=events.models.default_post_text),
        ),
    ]
