# Generated by Django 3.1.7 on 2024-05-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
