# Generated by Django 3.1.7 on 2024-05-24 11:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_testeventplace'),
        ('events', '0017_event_post_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsNotApprovedProposed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(default=events.models.random_event_id, max_length=30)),
                ('approved', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('post', models.TextField(blank=True, default='')),
                ('full_text', models.TextField(blank=True, default='', null=True, verbose_name='Текст мероприятия')),
                ('image', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка на изображение')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Ссылка на мероприятие')),
                ('price', models.CharField(blank=True, default='1000₽', max_length=500, verbose_name='Цена')),
                ('category', models.CharField(blank=True, max_length=500, null=True, verbose_name='Категория (тип мероприятия)')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Адрес')),
                ('explored_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published date and time')),
                ('from_date', models.DateTimeField(blank=True, default=events.models.default_event_date, null=True, verbose_name='Дата и время начала мероприятия')),
                ('to_date', models.DateTimeField(blank=True, default=events.models.default_event_date, null=True, verbose_name='Дата и время окончания мероприятия')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='place.place')),
            ],
        ),
        migrations.DeleteModel(
            name='EventsNotApprovedOld',
        ),
    ]
