# Generated by Django 3.1.7 on 2024-05-28 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20240524_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='events2post',
            name='post_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
