# Generated by Django 3.1.7 on 2024-05-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_events2post_post_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postingtime',
            name='posting_time',
            field=models.TimeField(null=True),
        ),
    ]
