# Generated by Django 3.1.7 on 2024-07-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_events2post_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='events2post',
            name='is_ready',
            field=models.BooleanField(default=False, null=False),
        ),
    ]
