# Generated by Django 3.1.7 on 2024-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_events2post_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='status',
            field=models.CharField(choices=[('ReadyToPost', 'Ready To Post'), ('Posted', 'Posted'), ('ForFuture', 'For Future'), ('Spam', 'Spam'), ('Scrape', 'Scrape It')], db_index=True, default='ReadyToPost', max_length=15),
        ),
    ]
