# Generated by Django 3.1.7 on 2024-08-05 09:36

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_auto_20240729_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events2post',
            name='event_id',
            field=models.CharField(db_index=True, default=events.models.random_event_id, max_length=30),
        ),
    ]
