version: '3.8'
services:
   web:
       build: .
       command: gunicorn --bind :8000 --workers 3 dsn_django.wsgi:application
       volumes:
         - /:/dsn_django/static
       ports:
           - 8000:8000
