version: '3.8'
services:
   web:
       build: .
       expose:
         - "8000"
       env_file: .env
       environment:
        DEBUG: 'false'
       volumes:
         - web-static:/dsn_django/static/
         - web-volume:/dsn_django/static/
       ports:
           - "8000:8000"
       command: gunicorn --bind :8000 --workers 3 dsn_django.wsgi:application
       networks:
         - django-network

   nginx:
     build: ./nginx/
     restart: always
     ports:
       - "8080:8080"
     volumes:
       - web-static:/dsn_django/static/
       - web-volume:/dsn_django/static/
     links:
       - web:web
     networks:
       - django-network
networks:
  django-network:
    name: django-network

volumes:
  web-volume:
  web-static:
