# Generated by Django 4.2 on 2026-09-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_generator", "0002_generatedpost_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filterset",
            name="filter_type",
            field=models.CharField(
                choices=[
                    ("standard", "Стандартный"),
                    ("custom", "Пользовательский"),
                    ("semantic", "Семантический (тема дайджеста)"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="postingschedule",
            name="platform",
            field=models.CharField(
                choices=[("telegram", "Telegram"), ("vk", "VK")],
                default="telegram",
                help_text="telegram, vk, etc.",
                max_length=50,
                verbose_name="Платформа",
            ),
        ),
    ]
