# Generated by Django 3.1.7 on 2023-03-10 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=500)),
                ('place_address', models.CharField(blank=True, max_length=2000)),
                ('place_url', models.CharField(blank=True, max_length=500)),
                ('url_to_address', models.CharField(blank=True, max_length=500)),
                ('place_metro', models.CharField(blank=True, max_length=500)),
                ('place_city', models.CharField(blank=True, default='SPb', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_keyword', models.CharField(max_length=200)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.place')),
            ],
        ),
    ]
