# Generated by Django 3.1.7 on 2023-03-10 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestEventPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('event_address', models.CharField(max_length=200)),
                ('place_keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.placekeyword')),
            ],
        ),
    ]
